# Generated by Django 4.1.7 on 2023-05-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.deliveryaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date_and_time',
            field=models.DateTimeField(null=True),
        ),
    ]
