# Generated by Django 4.1.7 on 2023-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date_and_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time2',
            field=models.TimeField(null=True),
        ),
    ]
