# Generated by Django 4.1.7 on 2023-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_delivery_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default='в обработке'),
        ),
    ]
