# Generated by Django 4.1.7 on 2023-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в обработке', 'в обработке'), ('в сборке', 'в сборке'), ('в доставке', 'в доставке'), ('выполнен', 'выполнен'), ('отменён', 'отменён')], default='в обработке', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
