# Generated by Django 4.1.7 on 2023-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_basketitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
