# Generated by Django 4.1.7 on 2023-05-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0008_alter_basketitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='basket_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product'),
        ),
    ]
