# Generated by Django 4.1.7 on 2023-05-31 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0009_remove_basketitem_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product'),
            preserve_default=False,
        ),
    ]
