# Generated by Django 4.1.7 on 2023-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_and_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('клиент', 'клиент'), ('менеджер', 'менеджер'), ('администратор', 'администратор')], max_length=150, null=True),
        ),
    ]
