# Generated by Django 4.1.7 on 2023-03-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'aspect_ratio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'case',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComputerKitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'computer_kit_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Connectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'connectors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CurvedScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'curved_screen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diagonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'diagonal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'fan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FrameColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'frame_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'keyboard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatrixType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'matrix_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'memory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'monitor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.aspectratio')),
                ('connectors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.connectors')),
                ('curved_screen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.curvedscreen')),
                ('diagonal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.diagonal')),
                ('frame_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.framecolor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer')),
                ('matrix_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.matrixtype')),
            ],
            options={
                'db_table': 'monitor_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'motherboard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'mouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpticalDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'optical_drive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'processor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScreenResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'screen_resolution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoundAndNetworkCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'sound_and_network_card',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'speakers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'storage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UpdateFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'update_frequency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'video_card',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WallMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'wall_mount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemUnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.case')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.fan')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.memory')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.motherboard')),
                ('optical_drive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.opticaldrive')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.processor')),
                ('sound_and_network_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.soundandnetworkcard')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.storage')),
                ('video_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.videocard')),
            ],
            options={
                'db_table': 'system_unit_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=500)),
                ('detailed_description', models.CharField(max_length=3000)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(choices=[('компьютеры в комплекте', 'компьютеры в комплекте'), ('системные блоки', 'системные блоки'), ('мониторы', 'мониторы'), ('спецпредложения', 'спецпредложения')], max_length=150)),
                ('computer_kit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.computerkitdetails')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.monitordetails')),
                ('system_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.systemunitdetails')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='monitordetails',
            name='screen_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.screenresolution'),
        ),
        migrations.AddField(
            model_name='monitordetails',
            name='update_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.updatefrequency'),
        ),
        migrations.AddField(
            model_name='monitordetails',
            name='wall_mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.wallmount'),
        ),
        migrations.AddField(
            model_name='computerkitdetails',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.keyboard'),
        ),
        migrations.AddField(
            model_name='computerkitdetails',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.monitor'),
        ),
        migrations.AddField(
            model_name='computerkitdetails',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.mouse'),
        ),
        migrations.AddField(
            model_name='computerkitdetails',
            name='speakers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.speakers'),
        ),
        migrations.AddField(
            model_name='computerkitdetails',
            name='system_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.systemunitdetails'),
        ),
    ]
