# Generated by Django 4.1.7 on 2023-04-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfRAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'amount_of_ram',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HDDVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'hdd_volume',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcessorSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'processor_series',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SSDVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'ssd_volume',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemUnitFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('для дома', 'для дома'), ('для офиса', 'для офиса'), ('для игр', 'для игр')], max_length=150, null=True)),
                ('amount_of_ram', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.amountofram')),
                ('hdd_volume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.hddvolume')),
                ('processor_series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.processorseries')),
                ('ssd_volume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.ssdvolume')),
            ],
            options={
                'db_table': 'system_unit_filters',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='case',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='optical_drive',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='sound_and_network_card',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='systemunitdetails',
            name='video_card',
        ),
        migrations.AlterField(
            model_name='videocard',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='OpticalDrive',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='SoundAndNetworkCard',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.AddField(
            model_name='systemunitfilters',
            name='video_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.videocard'),
        ),
        migrations.AlterField(
            model_name='computerkitdetails',
            name='system_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.systemunitfilters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='system_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.systemunitfilters'),
        ),
        migrations.DeleteModel(
            name='SystemUnitDetails',
        ),
    ]
