# Generated by Django 4.1.7 on 2023-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_monitordetails_diagonal_delete_diagonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordetails',
            name='curved_screen',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='CurvedScreen',
        ),
    ]
