# Generated by Django 4.1.7 on 2023-06-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_monitordetails_curved_screen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerkitdetails',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.monitordetails'),
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
