# Generated by Django 4.1.7 on 2023-06-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_computerkitdetails_monitor_delete_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitordetails',
            name='connectors',
        ),
        migrations.DeleteModel(
            name='Connectors',
        ),
    ]
