# Generated by Django 4.1.7 on 2023-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_systemunitdetails_hdd_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemunitdetails',
            name='hdd_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemunitdetails',
            name='ssd_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HDDVolume',
        ),
        migrations.DeleteModel(
            name='SSDVolume',
        ),
    ]
